/**
**@version 1.3
**@date 2010/07/14
**@author junxue.rao
*/


  CREATE TABLE "STATE"."ENTRY_COMMENT" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"ADDTIME" DATE, 
	"AUDITED" NUMBER(1,0) NOT NULL ENABLE, 
	"CONTENT" CLOB, 
	"ENTRYID" NUMBER(10,0), 
	"IP" VARCHAR2(255 BYTE), 
	"USERNAME" VARCHAR2(255 BYTE), 
	"VOTE" NUMBER(10,0) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" 
 LOB ("CONTENT") STORE AS (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) ;
  
  commit;
  
  alter table "STATE"."SYSTEMINFO" add "SYSTEMINFO_DESCRIPTION" VARCHAR2(255 BYTE) default null;
  alter table "STATE"."SYSTEMINFO" add "SYSTEMINFO_ALLOWCOMMENT" NUMBER(1,0);
  REM INSERTING into "STATE"."SYSTEMINFO"
  update "STATE"."SYSTEMINFO" set "SYSTEMINFO_ALLOWCOMMENT" = 0 where ID is not null;
  commit;
  
alter table "STATE"."ENTRY" add "ENTRY_DESCRIPTION" VARCHAR2(255 BYTE) default null;
alter table "STATE"."ENTRY" add "ENTRY_KEYWORD" VARCHAR2(255 BYTE) default null;
commit;

alter table Node add ORDERS VARCHAR2(255 BYTE) DEFAULT 'PUBLISHEDTIME';
alter table Entry add position NUMBER(*,0) DEFAULT 0;
commit;